#!/bin/bash
set -e

echo "🔧 Setting up QR Code Generator MCP App..."
echo ""

# Install dependencies
echo "📦 Installing dependencies..."
npm install

# Build UI and server
echo "🎨 Building UI and compiling server..."
npm run build

echo ""
echo "✅ Setup complete!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 Choose your deployment method:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "☁️  OPTION 1: Remote Server (Recommended)"
echo "   Deploy to Vercel for cloud hosting"
echo "   See: DEPLOY_TO_VERCEL.md for step-by-step guide"
echo ""
echo "💻 OPTION 2: Local Server"
echo "   Run on your machine with Claude Desktop"
echo ""
echo "   1. Add to Claude Desktop config:"
echo "      macOS: ~/Library/Application Support/Claude/claude_desktop_config.json"
echo "      Windows: %APPDATA%\\Claude\\claude_desktop_config.json"
echo ""
echo "   2. Add this configuration:"
echo "   {"
echo "     \"mcpServers\": {"
echo "       \"qrcode-generator\": {"
echo "         \"command\": \"npx\","
echo "         \"args\": [\"tsx\", \"$(pwd)/main.ts\", \"--stdio\"]"
echo "       }"
echo "     }"
echo "   }"
echo ""
echo "   3. Restart Claude Desktop"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 Test your server:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run HTTP server (for testing):"
echo "  npm run dev"
echo "  Then visit: http://localhost:3001/health"
echo ""
echo "Run stdio server (for Claude Desktop):"
echo "  npm run dev:stdio"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 You're ready to generate QR codes!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
